### ISSUE TITLE
Data architecture of the OEDI project

### ISSUE THREAD

**Issue by Sander3003** [openEDI/documentation#8]
HI LF energy OEDI project,

From de LF energy data architecture working group, we are interested in the data architecture of the OEDI project. This could be input for the LF energy data architecture framework and improve the interopbaiblity of the LF energy projects. 

https://wiki.lfenergy.org/display/HOME/Data+Architecture+Working+Group

Can someone give a presentation around these OEDI topics for the LF energy data architecture workgroup and join the office our to present it?

- Project introduction
- Data input
- Data output
- Used semantics (What standards are used? e.g. for the meta data catalog)

**Comment by MRossol** [comment]
Hi @Sander3003 more than happy to present on OEDI to the LF Energy Data Architecture Working Group. Mind sending me an e-mail (michael.rossol@nrel.gov) with potential dates and how long you want us to talk for?

**Comment by Sander3003** [comment]
Hi Michael,

As discussed on Github, we have a weekly office hour.
https://wiki.lfenergy.org/display/HOME/Data+Architecture+Working+Group

Teleconference weekly on Thursdays, 7:00 US Pacific Time

It would be nice if you can join tomorrow. If that is too early, you can pick another date. 

30 minutes presentation and 20 minutes discussion?
We are most interested in the semantic side; what semantics are used and why.
